Feature/JC19-326-creating-anime-table
saritasa-nest/camp-js-2022-bogdan-krasnov pull request #1
Opened 2022-07-06 15:47 UTC by BKrasnov

2022-07-07 05:20 UTC, panov-aleksey-saritasa commented
Hi!
1. We didn't take into account Draft PRs, action that invites reviewers does not check this scenario, sorry 🥲. Artem wrote how to fix it here https://saritasa.slack.com/archives/C02UTQPRW7R/p1657169986282109
2. You `linting.yml` contains invisible characters (line 2, 7 and etc), because of that action does not work, please remove them
![image](https://user-images.githubusercontent.com/86595878/177697008-2d46a6ea-c721-44a1-be76-23a434c6a50f.png)
3. To invite other guys to review automatically,

2022-07-07 07:18 UTC, timofei-maximov-saritasa requested changes

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/table.ts
> +   * SetPagination function.
Let's improve method description

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +export function creatingButtonPagination(dataText: string,
Please, stick with [this naming pattern](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#ahclc-pattern)

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  const countedDynamicButtons = [];
Please, specify array type. [Here is small example](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhgJwXAnjAvDA2gXQNwCwAUMYsigHQAOArhABYAUA5NAgJZgDmzAlKUlTU6TAIz8iZIbQaMA3hBABbAKYBpFSgBcMZoD4NwCi7zAL68gA) why we need to specify type in case of arrays.

TLDR, array type is `any`

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> + * Refresh current page function.
No need to write `function` in your doc strings.

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> +const setAnimeAsync = async(response: Promise<PaginationDto<Anime>>): Promise<void> => {
There is no need to use `async` in function name.

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> +const setAnimeAsync = async(response: Promise<PaginationDto<Anime>>): Promise<void> => {
It's weird that you pass a promise to your function. Also, you violated abstraction: you are using `dto` in your UI layer.

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> +    (await response).results.forEach((anime: Anime) => renderAnime(anime));
Please, don't use type annotation here, let typescript handle it.

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> + * Anime rendering function.
Let's improve description. For example, `Render single anime.`

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> +    <td class="image"><img src="${image}" alt=""></td>
Missing `alt` attribute.

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> +}
Let's move this to utils, because it can be reused

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +  readonly start: string | null;
Missing docs

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on libs/core/mappers/anime.mapper.ts
> +      aired: dto.aired,
Your `AnimeDto` has `string | null` type for `aired.start` but your model has `Date` type. Please, fix it.

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on libs/core/mappers/pagination.mapper.ts
> +  }
Your pagination mapper works only with `AnimeDto` but it accepts generic. Let's improve this behaviour to make this mapper more flexible and reusable.

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on libs/core/models/anime.ts
> +  public readonly id: number | undefined;
Why do you have `number | undefined` type here?

2022-07-07 07:18 UTC, timofei-maximov-saritasa commented on libs/core/models/anime.ts
> +  /** Type. */
These doc strings are not very informative

2022-07-07 09:31 UTC, artem-sotnichenko-saritasa requested changes

2022-07-07 09:31 UTC, artem-sotnichenko-saritasa commented on .gitignore
> +apps/vanilla/src/vite-env.d.ts
You should ignore env variables but not the typings.

2022-07-07 09:31 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/.stylelintrc.json
> +  }
Please revert changes here. You have root `.stylelintrc.json` that is source of truth, and you app's config should inherit root config.

2022-07-07 09:31 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +  margin: 50px 0 0 0;
Please move colors into variables.

2022-07-07 09:31 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.ts
> +function tableAnime(): Table {
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#naming-functions

2022-07-07 09:31 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/table.ts
> + * @param currentSorting Current sorting.
You should document class properties right in the class, like so:
```js
  /** Current Page. */
  private currentPage: number;

2022-07-07 09:31 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/table.ts
> +  private currentSorting: string;
Please place properties above constructor, methods below constructor.

If you modify(set) property only in the constructor, you should add `readonly` modifier to the property.

2022-07-07 12:19 UTC, BKrasnov commented on libs/core/models/anime.ts
> +  public readonly id: number | undefined;
Can I delete this property since it is not being used?

2022-07-07 13:25 UTC, panov-aleksey-saritasa commented
@BKrasnov Please, don't forget about linting errors https://github.com/saritasa-nest/camp-js-2022-bogdan-krasnov/runs/7233104038?check_suite_focus=true

2022-07-08 06:00 UTC, dmitriqm commented on apps/vanilla/src/core/constants/anime.ts
> +export const QUANTITY_ANIME = 24200;
The count of anime is subject to change.
you need to get it from api

2022-07-08 06:25 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/core/utils/api.ts
> +  currentPage = CURRENT_PAGE_DEFAULT,
Function gets a lot of parameters, it is better use object.

2022-07-08 06:33 UTC, golovachev-yaroslav requested changes

2022-07-08 06:33 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +.image img{
`.image` looks like a wrapper, please add more informative name.

2022-07-08 06:33 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +  background-color: #966BD6;
Please use css var.

2022-07-08 06:33 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +}
Please add empty space after each selector
```
.pagination {...

.some {...

.another {...
```

2022-07-08 06:33 UTC, golovachev-yaroslav commented on libs/core/models/anime.ts
> +  public readonly id: number | undefined;
`public readonly id?: number;` - it could looks like this.

2022-07-11 08:42 UTC, elena-dragunova requested changes

2022-07-11 08:42 UTC, elena-dragunova commented on apps/vanilla/src/pages/index.css
> +  background-color: #4F10AD;
Use variables for colors please.

2022-07-11 15:08 UTC, maxineo commented on libs/core/dtos/anime.dto.ts
> +  readonly end: Date;
These should be strings since you cannot get `Date` objects from the server.

2022-07-12 03:22 UTC, BKrasnov commented on apps/vanilla/src/scripts/table.ts
> + * Refresh current page function.
Why?

2022-07-12 05:08 UTC, BKrasnov commented on .gitignore
> +apps/vanilla/src/vite-env.d.ts
Need to write ".env"?

2022-07-12 05:35 UTC, BKrasnov commented on apps/vanilla/src/scripts/table.ts
> +    const tbody = document.querySelector<HTMLTableElement>('tbody');
I didn't understand

2022-07-12 07:45 UTC, maxineo commented on apps/vanilla/src/scripts/table.ts
> +    const tbody = document.querySelector<HTMLTableElement>('tbody');
For example `document.querySelector<HTMLTableElement>('.anime-table');`.

2022-07-12 08:42 UTC, maxineo requested changes

2022-07-12 08:42 UTC, maxineo commented on apps/vanilla/src/global/variables.css
> +  --heading-color-3: #4F10AD;
Please add some meaningful prefix for your colors instead of just `1` and `3`

2022-07-12 08:42 UTC, maxineo commented on apps/vanilla/src/global/variables.css
> +  --footer-color-1: #300571;
The same with prefix

2022-07-12 08:42 UTC, maxineo commented on apps/vanilla/src/global/variables.css
> +  --font-size-1: 1em;
It would be easier to work with `rem` here.

2022-07-12 08:42 UTC, maxineo commented on apps/vanilla/src/global/variables.css
> +  --font-size-1: 1em;
The same with prefix. For font-sizes you can use similar approach to font-weight. For example:
`--font-size-300: 0.75rem`
`--font-size-400: 1rem;`
`--font-size-500: 1.25rem;`
`--font-size-600: 1.5rem;`

2022-07-12 08:42 UTC, maxineo commented on apps/vanilla/src/pages/index.css
>  }
Do you really need that for all select elements?

2022-07-12 08:42 UTC, maxineo commented on apps/vanilla/src/pages/table.ts
> +  private isLoading: boolean;
You still dont use it. Why do you need it?

2022-07-12 08:42 UTC, maxineo commented on apps/vanilla/src/pages/table.ts
> +    if (this.currentPage === CURRENT_PAGE_DEFAULT) {
I think it is better to add a different const for this

2022-07-12 08:42 UTC, maxineo commented on apps/vanilla/src/scripts/table.ts
> +const setAnime = async(response: Promise<PaginationDto<Anime>>): Promise<void> => {
Please change this function to not accept promise, and dont use dto in your ui layer.

2022-07-12 08:52 UTC, BKrasnov commented on apps/vanilla/src/pages/table.ts
> +  private isLoading: boolean;
Ok, I'll delete it. I wanted to do this in the future

2022-07-12 09:04 UTC, BKrasnov commented on apps/vanilla/src/core/utils/api.ts
> +  const { currentPage = CURRENT_PAGE_DEFAULT, ordering = Ordering.None, limit = PAGE_SIZE_DEFAULT } = paginationConfig;
Where is it better to create it? In getAnimeData?

2022-07-12 16:44 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> + * Refresh current page function.
@BKrasnov We can see that this is a function, so there is no need to specify it your docs

2022-07-12 16:44 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> + * A function that transmits data for rendering anime.
Same about writting `function` in your docs

2022-07-12 16:44 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> +const setAnime = (response: PaginationDto<Anime>): void => {
Please, be consistent declaring your functions. As I can see, you use [function declaration](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#function_declarations) in other places in your code, so stick with this approach.

2022-07-12 16:44 UTC, timofei-maximov-saritasa commented on libs/core/models/anime.ts
> +  public readonly titleEng: string;
Please, [avoid contractions](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions)

2022-07-12 16:44 UTC, timofei-maximov-saritasa commented on libs/core/mappers/pagination.mapper.ts
> +   * Maps dto to model.
Please, be consistent with verb endings. You have somewhere description with `Create button ...`, but here you have `Maps dto ...`

2022-07-13 05:21 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/global/variables.css
> +  --footer-color-1: #300571;
https://github.com/saritasa-nest/camp-js-2022-sofya-kirillova/pull/1#discussion_r913371318

2022-07-13 05:21 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/core/utils/date.ts
> + * Converting data to date format.
As I see, it does not convert data to date formate, but rather convert a date to some string format

2022-07-13 05:21 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/core/utils/date.ts
> + * @param dateReceived Data coming from the server .
I think functions shouldn't know where their arguments are coming from

2022-07-13 05:21 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/core/utils/axiosInstance.ts
> + */
Prefer inline docs: https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#docstring-or-inline

2022-07-13 05:21 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/core/utils/api.ts
> +  return PaginationMapper.fromDto<AnimeDto, Anime>(
Typescript could infer generics here by itself, it checks what types passed arguments have
```suggestion
  return PaginationMapper.fromDto(
```

2022-07-13 05:21 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/core/utils/api.ts
> +  const urlAnime = new URLSearchParams(`limit=${limit}&offset=${offset}&ordering=${ordering.concat(',')}id`);
There is no much sense in using `URLSearchParams` if you don't use its API
Please, check out the [append](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/append) method

2022-07-13 05:21 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/table.ts
> +    this.quantityAnime = 24200;
how does your table class knows that exact amount of animes is `24200`? 🤔

2022-07-13 05:21 UTC, panov-aleksey-saritasa commented on libs/core/mappers/anime.mapper.ts
> +      // I don't know yet how to solve it so that there is an assignment between different types.
It's not clear what your problem is

2022-07-13 06:08 UTC, BKrasnov commented on .gitignore
> +.env
I didn 't write the file initially .env in .gitignore and it could go to a remote repository. Could this be a problem?

2022-07-13 06:45 UTC, BKrasnov commented on libs/core/mappers/anime.mapper.ts
> +      // I don't know yet how to solve it so that there is an assignment between different types.
I have underscores for type and status: 
Type 'string' is not assignable to type 'AnimeType' or 'AnimeStatus'

2022-07-13 06:46 UTC, BKrasnov commented on .gitignore
> +.env
I didn 't write the file initially .env in .gitignore and it could go to a remote repository. Could this be a problem?

2022-07-13 06:55 UTC, golovachev-yaroslav requested changes

2022-07-13 06:55 UTC, golovachev-yaroslav commented on apps/vanilla/src/global/variables.css
> +  --font-size-400: 1rem;
Not obvious name, why 400?

2022-07-13 06:55 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +select {
Please avoid styles to tag, it would be better to implement via CSS class.

2022-07-13 06:55 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/pagination.ts
> +export function creatingPaginationButton(dataText: string,
Functions must starts with a verb.
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming/#ahclc-pattern

2022-07-13 06:55 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/pagination.ts
> +  let j = 0;
Much better to rename `j` for more informative.

2022-07-13 15:37 UTC, timofei-maximov-saritasa commented on libs/core/mappers/anime.mapper.ts
> +      // I don't know yet how to solve it so that there is an assignment between different types.
@BKrasnov It is because you get string from server, but your model expects that you will pass `AnimeType`/`AnimeStatus`. You need to validate if your data from server is valid because you may get value that is not represented in your `enum`. For example, you can implement mapper for your enum using `switch/case`. Or you can do it in any other way

2022-07-17 17:34 UTC, artem-sotnichenko-saritasa requested changes

2022-07-17 17:34 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  const countedDynamicButtonsWithPoints: Array<number | string> = [];
Please be consistent, choose `Array<T>` or `T[]` syntax

2022-07-17 17:34 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/table.ts
> +  const ordering = currentSorting;
`currentSorting: Ordering` looks strange. Why do you need to name it `currentSorting` and than assign into `ordering`.

2022-07-18 02:17 UTC, panov-aleksey-saritasa requested changes

2022-07-18 02:17 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.ts
> +}
Not sure why do you need to return `Table`, it seems all you need it is just instantiate it

2022-07-18 02:17 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/table.ts
> +   */
```suggestion
  /** Creates pagination buttons for anime table. */
```

2022-07-18 02:17 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/table.ts
> +    if (tbody.childElementCount < 5) {
What is `5`? Please, avoid magic numbers

2022-07-18 02:17 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/table.ts
> +    <td class="imageAnime"><img src="${image}" alt="Anime image"></td>
Change to `alt=""`, since this image has only decorative purpose
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML#alternative_text

2022-07-18 02:17 UTC, panov-aleksey-saritasa commented on libs/core/models/anime.ts
> +  public readonly image: string;
In my opinion `image` is a bit incorrect name here. What you probably meant here is `imageSrc` or `imageUrl`, right?

2022-07-18 02:17 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> + */
1. Don't start function docs with gerund, use base form of verbs instead
2. If you use `@returns`, provide more meaningful docs, it's not clear what these *strings or numbers* are about

2022-07-18 10:39 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/global/variables.css
> +  --font-size-400: 1rem;
Let's use semantic names for variables like `--font-size-xl`.

2022-07-18 10:39 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/global/variables.css
> +  --font-size-400: 1rem;
Please, don't resolve conversation like this. It's not clear why you have these numbers in variable names. So either add comment in code, or respond in github

2022-07-18 17:14 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/pages/table.ts
> +   * Checks what the current page is equal to.
it looks like the description does not match the meaning of the function

2022-07-19 03:57 UTC, BKrasnov commented on libs/core/models/anime.ts
> +  public readonly image: string;
Good. And what could have the name image?

2022-07-19 04:47 UTC, BKrasnov commented on apps/vanilla/src/global/variables.css
> +  --font-size-400: 1rem;
Okay, Maxim Korkin suggested that I write like this

2022-07-19 04:49 UTC, BKrasnov commented on apps/vanilla/src/core/utils/api.ts
> +  } = paginationConfig;
I fixed it a little differently

2022-07-19 05:00 UTC, BKrasnov commented on apps/vanilla/src/scripts/table.ts
> +    <td class="imageAnime"><img src="${image}" alt="Anime image"></td>
Timofey Maksimov said that the attribute is missing. Change?
https://github.com/saritasa-nest/camp-js-2022-bogdan-krasnov/pull/1#discussion_r915535227

2022-07-19 06:26 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/table.ts
> +    <td class="imageAnime"><img src="${image}" alt="Anime image"></td>
Yes, I think you should. Make sure you read it https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Images_in_HTML#alternative_text though

2022-07-19 08:12 UTC, BKrasnov commented on apps/vanilla/src/pages/index.ts
> +}
Solved in Slack

2022-07-20 02:42 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/core/utils/api.ts
> +import { PaginationMapper } from '@js-camp/core/mappers/pagination.mapper';
Please, do not keep API-related things in `utils` folder. Usually we use `utils` for simple pure util functions that could be used across the whole app

2022-07-20 02:42 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/core/utils/api.ts
> +  readonly ordering?: Ordering;
It's not clear what does *Ordering page* mean.

2022-07-20 02:42 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/core/utils/api.ts
> +  readonly ordering?: Ordering;
Consider separating ordering and pagination, they are unrelated things to each other.

2022-07-20 02:42 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/core/utils/axiosInstance.ts
> +export const apiAnime =
What do you mean by *Prepared data*?

2022-07-20 02:42 UTC, panov-aleksey-saritasa commented on libs/core/mappers/anime.mapper.ts
> +      status: Object.values(AnimeStatus).includes(dto.type as AnimeStatus) ? dto.type as AnimeStatus : AnimeStatus.NotYetAired,
Usually, we move out such things into separate functions, so we can avoid code duplication if we would need to do this check somewhere else

2022-07-20 02:42 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> + * @param disabled Disabled button.
Usually, to improve readability we use `is`, `should`, `can` and etc. prefixes for boolean variables and parameters.
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#prefixes

2022-07-20 02:42 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.html
> +      <nav></nav>
Empty `<nav>`. Is it intended?

2022-07-20 02:42 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.css
> +
Consider improving naming:
- there is no need to duplicate `-anime` suffix, you already did this for `table-anime`
- consider using more meaningful and semantically correct names instead of `thead` or `td`

2022-07-20 02:42 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.html
> +      <option value="-title_eng">Title english</option>
what is `-` in `-title_eng`?

2022-07-20 02:42 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.html
> +      <option value="-title_eng">Title english</option>
also consider creating options in your ts file rather than in HTML

2022-07-20 03:37 UTC, BKrasnov commented on apps/vanilla/src/core/utils/api.ts
> +import { PaginationMapper } from '@js-camp/core/mappers/pagination.mapper';
is it correct to move the api.ts to the scripts folder?

2022-07-20 03:41 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/core/utils/api.ts
> +  currentPageDefault: FIRST_PAGE,
It isn't clear why there are two constant CURRENT_PAGE_DEFAULT and FIRST_PAGE, but for currentPageDefault you use FIRST_PAGE, do you really need both that constant?

2022-07-20 03:43 UTC, BKrasnov commented on libs/core/mappers/anime.mapper.ts
> +      status: Object.values(AnimeStatus).includes(dto.type as AnimeStatus) ? dto.type as AnimeStatus : AnimeStatus.NotYetAired,
Okay, I'll take this function out to utils

2022-07-20 03:46 UTC, BKrasnov commented on apps/vanilla/src/pages/index.html
> +      <nav></nav>
I did this for the next task, I think I need to delete

2022-07-20 03:50 UTC, BKrasnov commented on apps/vanilla/src/pages/index.css
> +
thead -> top-row, td - cell? Good?

2022-07-20 03:55 UTC, BKrasnov commented on apps/vanilla/src/core/utils/api.ts
> +  currentPageDefault: FIRST_PAGE,
It will be correct: currentPageDefault: CURRENT_PAGE_DEFAULT,
I'll fix it

2022-07-20 03:57 UTC, BKrasnov commented on apps/vanilla/src/core/utils/api.ts
> +  currentPageDefault: FIRST_PAGE,
Yes, because in the code I compare currentPage with FIRST_PAGE
(pages/table.ts in updatePagination)

2022-07-20 18:33 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-28 08:57 UTC, chernodub commented on apps/vanilla/src/core/constants/anime.ts
> +export const NEXT_PAGE = '>>';
Please don't rely on Unicode when creating buttons (especially, don't store it in JS). What if, at some point, a client decides to ask you to add an svg?

2022-07-28 08:57 UTC, chernodub commented on apps/vanilla/src/core/constants/anime.ts
> +export const NEXT_PAGE = '>>';
Also, don't make a constant global, if it's used in a single place. There is simply no point exposing it into the global scope if nobody cares about it, stick to that rule of thumb for every exportable entity

2022-07-28 08:57 UTC, chernodub commented on apps/vanilla/src/global/base.css
> +  font-size: var(--font-size-1);
For some reason, I don't see such variable in `apps/vanilla/src/global/variables.css`, is this a mistake?

2022-07-28 08:57 UTC, chernodub commented on apps/vanilla/src/pages/index.css
> +  border: 1px solid var(--primary-dark-contrast-color);
Usually, contrast colors are used for fonts or some elements that should be visible on the color. For the table, I'd recommend creating a second color, usually we stick to `primary`/`accent`/`tertiary` [naming convention](https://wiki.saritasa.rocks/frontend/languages/css#naming)

2022-07-28 08:57 UTC, chernodub commented on apps/vanilla/src/pages/table.ts
> +export class Table {
Seems like this name is too generic for your application, what if at some point, there's a task to add a table of anime genres?

2022-07-28 08:57 UTC, chernodub commented on apps/vanilla/src/pages/table.ts
> +  private readonly quantityPage: number;
The name here sounds a bit incorrect to hear. Usually we use something like `pagesAmount`, `pagesNumber` or `totalPages` or, like in your case `pageQuantity` (but usually it's `amount` or `total`)

2022-07-28 08:57 UTC, chernodub commented on apps/vanilla/src/pages/table.ts
> +  private readonly quantityPage: number;
No need to fix this, but just keep that in mind for future :)

2022-07-28 08:57 UTC, chernodub commented on apps/vanilla/src/pages/table.ts
> +  public constructor(quantityAnime: number) {
Please prefer [shorthand for initializing ordered properties](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#prefer-shorthand-for-initializing-ordered-properties)

2022-07-28 08:57 UTC, chernodub commented on apps/vanilla/src/pages/table.ts
> +    this.sortAnimeList();
Please try to logically separate your code blocks, for example the first block could initialize variables and the second one could wire-up the DOM and etc. This would make your code more readable/maintainable

2022-07-28 08:57 UTC, chernodub commented on apps/vanilla/src/pages/table.ts
> +    for (const type in Ordering) {
Please try adding number to your enum values and see what happens :)

2022-07-28 08:57 UTC, chernodub commented on libs/core/mappers/anime.mapper.ts
> +    checkAnimeProperty(dto.type, dto.status);
Not sure I understand why is this needed, could you please elaborate?

2022-08-29 07:57 UTC, closed without merging