Feature/JC19-362-filtering-by-type
saritasa-nest/camp-js-2022-bogdan-krasnov pull request #2
Opened 2022-07-14 04:47 UTC by BKrasnov

2022-07-14 06:36 UTC, panov-aleksey-saritasa commented
@BKrasnov change target branch from the `develop` to the one, from which you created this feature branch

2022-07-17 13:15 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
>  th {
Please don't mix classes and tag names.
Also be consistent with class names, use kebab-case.

2022-07-17 13:15 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.html
> +          <h3>Select sorting</h3>
Don't skip heading levels, you should choose heading semantically and not by styles.

2022-07-17 18:25 UTC, timofei-maximov-saritasa requested changes

2022-07-17 18:25 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/core/utils/api.ts
> +  const urlAnime = `limit=${limit}&offset=${offset}&ordering=${ordering.concat(',')}id&type=${filtering}`;
Please, use `URLSerchParams`

2022-07-17 18:25 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> +}
```suggestion
export async function updateCountAnime(currentPage: number, ordering: Ordering, filtering?: AnimeType): Promise<number> {
  const { count }= await getAnimeData({ currentPage, ordering, filtering });
  return count;
}
```

2022-07-17 18:25 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/table.ts
> +export async function updateCountAnime(currentPage: number, currentSorting: Ordering, currentFilter?: AnimeType): Promise<number> {
How does it update anime count? It just returns count

2022-07-17 18:25 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/table.ts
> +   */
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#prefer-inline-when-possible

2022-07-18 06:55 UTC, BKrasnov commented on apps/vanilla/src/pages/index.css
>  th {
If I fixed it in task 1, then do I need to fix it here?

2022-07-18 14:48 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/core/utils/api.ts
>    /** Current page. */
Fix your docs, please

2022-07-21 18:37 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
>  th {
If it fixed in task 1, it's ok. But I would suggest merging it on this branch.

2022-07-21 19:45 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +          <h1>Select filter</h1>
I don't think `h1` headings are suitable here. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#multiple_h1_elements_on_one_page

> Using more than one `<h1>` is allowed by the HTML specification, but is not considered a best practice. Using only one `<h1>` is beneficial for screenreader users.

You can add `h1` inside `main` and hide it using `visually-hidden` pattern.

2022-07-21 19:49 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +  margin: 0 30px 0 0;
I think you can use just `margin-right: 30px`

2022-07-21 19:49 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +.filter__anime-table {
You can use `.sidebar__item` instead of `.sidebar__sort` and `.sidebar__filter`. Because you don't really need to distinguish them, and you have same styles.

2022-07-21 19:49 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.html
> +          <h1>Select filter</h1>
Page must have only one first-level heading.

2022-07-24 14:03 UTC, maxineo approved these changes

2022-08-29 07:59 UTC, closed without merging