Feature/JC19-393-initialize-anime-app-and-table-view
saritasa-nest/camp-js-2022-bogdan-krasnov pull request #5
Opened 2022-07-26 07:36 UTC by BKrasnov

2022-07-26 10:25 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +        </ng-container>
Format indentation properly

2022-07-26 10:25 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +    );
You can add `pipe` right away, without using variable.

2022-07-26 10:25 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    );
It is really strange that you are using `animeUpdated$` here. To get rid of it, make initial value of `isAnimeLoading$` `true`, than set it to `false` after get anime list.
```suggestion
    this.animeList$ = animeService.getAnimeList().pipe(
      tap(() => this.isAnimeLoading$.next(false))
    )
```

2022-07-26 10:54 UTC, BKrasnov commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    );
This code does not work, the variable isLoading remains false. I will remove this variable for now, but I will solve the problem in the future.

2022-07-26 14:54 UTC, BKrasnov commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public readonly isAnimeLoading$ = new BehaviorSubject<boolean>(false);
I will delete isAnimeLoading$
https://github.com/saritasa-nest/camp-js-2022-bogdan-krasnov/pull/5#discussion_r929793226

2022-07-27 04:11 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-27 04:11 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public readonly displayedColumns: string[] = ['imageSrc', 'titleEnglish', 'titleJapanese', 'type', 'status', 'airedStart'];
Either add `readonly` for array, or use `as const`.

2022-07-27 04:11 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public readonly isAnimeLoading$ = new BehaviorSubject<boolean>(false);
If you won't use loading logic in this PR, than remove unused property.

2022-07-27 09:59 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +    aria-label="Anime Table"
Missing trackby
https://material.angular.io/cdk/table/overview#trackby

2022-07-27 09:59 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +        <img class="anime-image" [src]="anime.imageSrc" alt="" />
Missing `alt`

2022-07-29 04:28 UTC, timofei-maximov-saritasa approved these changes

2022-07-29 08:12 UTC, dbitkovski requested changes

2022-07-29 08:12 UTC, dbitkovski commented on apps/angular/src/app/app.module.ts
> +    AppConfigService,
Why do you need to provide it manually? I see you use `providedIn: 'root'` for this class

2022-07-29 08:12 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime.component.ts
> +  styleUrls: [],
If you don't have style files you can remove this property

2022-07-29 08:12 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime.module.ts
> +/** Table view module. */
Your docstring does not match module name, please provide more descriptive comment :)

2022-07-29 08:12 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime.routing.ts
> +/** Table view module. */
Same about documentation

2022-07-29 08:12 UTC, dbitkovski commented on apps/angular/src/app/features/anime/anime.routing.ts
> +    children: [],
You don't need to use `children` property if your route does not have children :)

2022-07-29 08:12 UTC, dbitkovski commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +    <!-- Id Column -->
Not a big deal but I think these comments are redundant. Also, it does not match the column it describes

2022-07-29 08:12 UTC, dbitkovski commented on apps/angular/src/material/material.module.ts
> +  A11yModule,
I doubt that you use all these modules :)
If tree-shaking mechanism get rid of unused modules, everything's fine

2022-07-29 08:12 UTC, dbitkovski commented on apps/angular/src/environments/environment.ts
> + * on performance if an error is thrown.a
Remove :)

2022-08-01 01:08 UTC, pavel-romanov8 requested changes

2022-08-01 01:08 UTC, pavel-romanov8 commented on apps/angular/src/shared/components/not-found/not-found.component.ts
> + * NotFound component.
Usually, we are not sticking to any naming conventions in our docs strings, expect some code examples

2022-08-01 01:08 UTC, pavel-romanov8 commented on apps/angular/src/material/material.module.ts
> +export class MaterialExampleModule {}
Maybe the name was like that already, but what does _example_ mean, and why does it name like example module? Please, rename it in order to make name more representative

2022-08-01 01:08 UTC, pavel-romanov8 commented on apps/angular/src/material/material.module.ts
> +/** Material Angular Module. */
```suggestion
/** Material Angular module. */
```

2022-08-01 01:08 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +  /** Reception with a configured URL. */
The doc string is really confusing. Consider improving it in order to describe the method more precisely, because we can add such documentation for literary any method of a service, and it won't make much difference

2022-08-01 01:08 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +        .set('ordering', ORDERING_DEFAULT),
Are you sure that you want to use constant ordering for each request?

2022-08-01 02:32 UTC, thanhnguyen-saritasa commented on .gitignore
> +apps/angular/src/environments/environment.ts
I think we need it. please check

2022-08-01 05:14 UTC, BKrasnov commented on .gitignore
> +apps/angular/src/environments/environment.ts
I didn't understand what needs to be checked

2022-08-05 01:24 UTC, pavel-romanov8 commented on apps/angular/src/app/app.module.ts
> +const httpInterceptorProviders = [
Please, add type annotation for the providers array. We have specific type for the `Provider` and here it will be `Provider[]`. That way, we are improving type checking for each provider that we want to plug in here

2022-08-05 01:24 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.html
> +    aria-label="Anime Table"
Check your indentation

2022-08-05 01:24 UTC, pavel-romanov8 commented on apps/angular/src/shared/components/not-found/not-found.component.ts
> +  styleUrls: ['./not-found.component.css'],
I see that in the `AnimeTableComponent` you are using `OnPush` change detection strategy, but here and in `AnimeComponent` it is default. Please, choose one and stick to it everywhere

2022-08-05 01:24 UTC, pavel-romanov8 commented on apps/angular/env.d.ts
> +    NG_APP_API_URL: string;
We can declare them as read-only

2022-08-05 01:24 UTC, pavel-romanov8 commented on apps/angular/src/core/constants/anime-table.ts
> +export const ORDERING_DEFAULT = 'id';
Are you using it anywhere? The same goes for the `FIRST_PAGE`

2022-08-05 01:24 UTC, pavel-romanov8 commented on apps/angular/src/core/constants/anime-table.ts
> +export const PAGE_SIZE_DEFAULT = 5;
If you are using the constant only in 1 file, there is no need to move it to a separate one. Please, place it in the `AnimeService` locally

2022-08-05 01:24 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +  /** Getting a list of anime. */
```suggestion
  /** Get a list of anime. */
```

2022-08-05 08:42 UTC, chernodub approved these changes

2022-08-05 08:42 UTC, chernodub commented on .gitignore
> +apps/angular/src/environments/environment.ts
Is there a reason why this is ignored ? 🤔

2022-08-08 09:34 UTC, dbitkovski approved these changes

2022-08-08 09:34 UTC, dbitkovski commented on apps/angular/src/shared/components/not-found/not-found.component.html
> +</div>
Missed closing tabs

2022-08-10 02:49 UTC, pavel-romanov8 approved these changes

2022-08-15 09:10 UTC, merged