Feature/JC19-405-anime-list-management
saritasa-nest/camp-js-2022-bogdan-krasnov pull request #7
Opened 2022-08-06 09:15 UTC by BKrasnov

2022-08-07 15:38 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-07 15:38 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public filterType(selectTypeValue: MatSelectChange): void {
Please be consistent, you used "on" prefix for other callbacks.

2022-08-08 02:27 UTC, gevorg-gevorgyan-saritasa requested changes

2022-08-08 02:27 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  private readonly pageSearch$ = new BehaviorSubject(DEFAULT_SEARCH_VALUE);
Use `FormControl` for your search (instead of `ngModel`) and filter, please

2022-08-08 02:27 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +  public constructor(appConfig: AppConfigService, private readonly http: HttpClient) {
```suggestion
  public constructor(
    appConfig: AppConfigService, 
    private readonly http: HttpClient,
  ) {
```

2022-08-09 02:39 UTC, BKrasnov commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  private readonly pageSearch$ = new BehaviorSubject(DEFAULT_SEARCH_VALUE);
Use it the way it says here?
https://wiki.saritasa.rocks/frontend/frameworks/angular/best-practices/#reactive-forms

2022-08-11 03:50 UTC, panov-aleksey-saritasa requested changes

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> + */
[Prefer inline docs](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#docstring-or-inline)

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/anime.component.ts
> +})
I saw you setted the `onPush` change detection strategy as default on component generation which as great 🙂. But I'm not sure why it's missing here

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/anime.module.ts
> +import { AnimeComponent } from './anime.component';
Please, group imports of the same level together, the fewer unnecessary lines of code, the better

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/anime.routing.ts
> +@NgModule({
I suppose it's the anime routing module and it's unrelated to any table view

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public readonly pageType$ = new BehaviorSubject([] as AnimeType[]);
```suggestion
  /** Filtering by type on the page. */
  public readonly pageType$ = new BehaviorSubject<readonly AnimeType[]>([]);
```

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  /** Count of anime taken from the request. */
Your UI should not know about where a data comes from 🙃

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  public readonly pageSort$ = new BehaviorSubject(ORDERING_DEFAULT);
Instead of creating a lot of behavior subjects, how about combining all of them into single `searchParams` or `searchConfig` behavior subject, since anyway every change of any param triggers an anime list refetch. What do you think?

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  }
Usually on Angular projects we use the `on` prefix to name event handlers
```suggestion
  /** Searching input form controller. */
  public onAnimeSearchChange(): void {
    this.pageIndex$.next(INITIAL_PAGE);
    this.pageSearch$.next(this.searchValue);
  }
```

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +  ) {
If you don't use services anywhere except the constructor, you could remove `private readonly`. This way services would be treated as function arguments and won't be declared as class properties
```suggestion
  public constructor(
    animeService: AnimeService,
    searchParamsService: SearchParamsService,
  ) {
```

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/components/anime-table/anime-table.component.ts
> +    );
FYI, you could avoid using `tap` and `BehaviorSubject` here for the `animeCount$` (usually we try to avoid using `tap` and `BehaviorSubject` as much as possible because of side-effect they produce)
```ts
    const animePage$ = combineLatest([
      this.pageType$,
      this.pageSearch$,
      this.pageSort$,
      this.pageIndex$,
      this.pageSize$,
    ]).pipe(
      debounceTime(DEBOUNCE_TIME),
      switchMap(([pageType, pageSearch, pageSort, pageIndex, pageSize]) => {
        const params = this.searchParamsService.changeSearchParams(new PaginationParams({
          page: pageIndex,
          size: pageSize,
          sort: pageSort,
          search: pageSearch,
          type: pageType,
        }));
        return this.animeService.getAnimeList(params);
      }),
      // shareReplay is needed here so that animePage$ stream would be executed only once
      // between multiple subscribers (animeCount$ and animeList$ in this case)
      // https://www.learnrxjs.io/learn-rxjs/operators/multicasting/sharereplay
      shareReplay({ refCount: true, bufferSize: 1 })
    );
    
    this.animeCount$ = animePage$.pipe(map(page => page.count));
    this.animeList$ = animePage$.pipe(map(page => page.results));
```

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +      .get<PaginationDto<AnimeDto>>(this.animeListUrl.toString(), {
Your function consumers shouldn't know anything about `HttpParams`. Consider delegating creation of needed http params to the `getAnimeList` method itself

Also `HttpParams` type is too generic, it does not provide any meaningful information of what kind of params function expects.

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +   * @param params Anime params.
Why do you mean by *Reception*? The docs is too unclear, consider improving it

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/not-found/not-found.component.html
> +<p>not-found works!</p>
Is this component used anywhere? It seems incomplete to me

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/search-params.service.ts
> +    });
This function two unrelated things at the same time: updates query params and creates `HttpParams`, seems single responsibility principle is violated here

2022-08-11 03:50 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/search-params.service.ts
> +    });
Btw, why do you move this `HttpParams` creation stuff out in separate service, if it's tightly related to anime list fetch method in anime service?

2022-08-29 07:59 UTC, closed without merging